server:
  port: 8888
  context-path : /
  tomcat:
    max-http-post-size: 31457280
spring:
  application:
    name: rabbitMqServer
  http :
    encoding :
      force : true
      charset : UTF-8
      enabled : true
  datasource:
    type : com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.4.72:3306/chinaoly_sjzt_api
    username: root
    password: chinaoly
    druid :
      maxWait : 5000
      max-active : 500
      max-total : 500
      removeAbandoned : true
      removeAbandonedTimeout : 300
      logAbandoned : true
  redis :
    host : 192.168.1.146
    database : 0
    port : 6379
    timeout : 100000
    pool :
      max-idle : 10000
      min-idle : 50
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: /
    username: guest
    password: guest
    publisher-confirms: true
mybatis:
  type-aliases-package : com.chinaoly.frm.security.Model
logging :
  config : classpath:logback-spring.xml
eureka:
  client:
    enabled: true
    # 开启健康检查（依赖spring-boot-starter-actuator）
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://192.168.4.71:8761/eureka/
    # 默认为30秒
    registry-fetch-interval-seconds: 5
  instance:
    # 发呆时间，即服务续约到期时间（缺省为90s）
    lease-expiration-duration-in-seconds: 15
    # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-renewal-interval-in-seconds: 5
    # 注册是否显示IP地址
    prefer-ip-address: true
    #    instance-id: ${spring.application.name}:${server.port}
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    #    appname: ${spring.application.name}
    metadata-map:
      username: zhangsan
      addr: myAddr
      contextPath: ${server.context-path}
    health-check-url-path: ${server.context-path}/health
    status-page-url-path: ${server.context-path}/swagger-ui.html

#请求处理的超时时间
ribbon:
  ReadTimeout: 120000
  ConnectTimeout: 30000

feign:
  hystrix:
    enabled: true

#hystrix 熔断机制
hystrix:
  shareSecurityContext: true
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 100000
        forceClosed: true
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
#top.wboost包拦截放行
common:
  cloud:
    api:
      filter:
        whitelist:
          - "*"